# Generated by Django 3.0.8 on 2020-07-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetailrecord',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
