# Generated by Django 3.0.8 on 2020-07-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_auto_20200712_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='csv_file',
            field=models.FileField(upload_to=None),
        ),
    ]
