# Generated by Django 3.0.8 on 2020-07-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0004_auto_20200712_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='csv_file',
            field=models.FileField(upload_to='static/phonebooks'),
        ),
    ]
