# Generated by Django 3.0.8 on 2020-07-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0005_auto_20200712_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonebook',
            name='leads',
        ),
        migrations.AddField(
            model_name='lead',
            name='phonebook',
            field=models.ManyToManyField(related_name='leads', to='phonebook.Phonebook'),
        ),
    ]
