# Generated by Django 3.0.8 on 2020-07-12 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0008_auto_20200712_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phonebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='phonebook.Phonebook'),
        ),
    ]
