# Generated by Django 3.0.8 on 2020-07-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0009_auto_20200712_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
