# Generated by Django 3.0.8 on 2020-07-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0012_donotcall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetailrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
