# Generated by Django 3.0.8 on 2020-07-12 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0014_auto_20200712_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donotcall',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='phonebook.Lead'),
        ),
    ]
