# Generated by Django 3.0.8 on 2020-07-15 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0019_auto_20200713_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donotcall',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonebook.Lead'),
        ),
    ]
