# Generated by Django 3.0.8 on 2020-07-15 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0020_auto_20200715_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donotcall',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='phonebook.Lead'),
        ),
    ]
